= metafacture-xml-plugin
:toc:

A plugin for link:https://github.com/metafacture/metafacture-core[metafacture] that extends the standard XML module.

== Build

image::https://jitpack.io/v/eberhardtj/metafacture-xml-extension.svg[link="https://jitpack.io/#eberhardtj/metafacture-xml-extension"]

```
gradlew test fatJar
```

Produces `metafacture-xml-VERSION-plugin.jar` in `build/libs` .

Place the build JAR inside the `plugins` directory of your `metafacture-core` distribution.

== Command Reference

|===
|Command | In | Out

|split-sax
|XmlReceiver
|XmlReceiver

|split-xml
|Reader
|String

|stream-to-sax
|StreamReceiver
|XmlReceiver

|===

=== split-sax

==== Description

Yields a new document for each child element underneath the document root.

==== Syntax

```
split-sax
```

==== Example

Flux:

```
> | decode-xml | split-sax | ...
```


=== split-xml

==== Description

Yields a new document for each child element underneath the document root.

==== Syntax

```
split-xml
```

==== Example

Flux:

```
> | as-lines | split-xml | decode-xml | ...
```



=== stream-to-sax

==== Description

Converts metafacture records into XML events.

==== Syntax

```
stream-to-sax
```


==== Example

Flux:

```
... | stream-to-sax | ...
```


A serialized record after the conversion into xml events would look like the following example:

```xml
<record id="ID">
  <literal name="NAME">VALUE</literal>
  <entity name="NAME">
    <literal name="NAME">VALUE</literal>
  </entity>
</record>
```
